/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PresentationsRouteImport } from './routes/presentations'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as DomainRouteImport } from './routes/domain'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminPresentationsRouteImport } from './routes/admin.presentations'
import { Route as AdminMilestonesRouteImport } from './routes/admin.milestones'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminHomeRouteImport } from './routes/admin.home'
import { Route as AdminDomainRouteImport } from './routes/admin.domain'
import { Route as AdminDocumentsRouteImport } from './routes/admin.documents'

const PresentationsRoute = PresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainRoute = DomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPresentationsRoute = AdminPresentationsRouteImport.update({
  id: '/presentations',
  path: '/presentations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMilestonesRoute = AdminMilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDomainRoute = AdminDomainRouteImport.update({
  id: '/domain',
  path: '/domain',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/presentations': typeof PresentationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/domain': typeof AdminDomainRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/presentations': typeof AdminPresentationsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/presentations': typeof PresentationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/domain': typeof AdminDomainRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/presentations': typeof AdminPresentationsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/domain': typeof DomainRoute
  '/milestones': typeof MilestonesRoute
  '/presentations': typeof PresentationsRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/domain': typeof AdminDomainRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/milestones': typeof AdminMilestonesRoute
  '/admin/presentations': typeof AdminPresentationsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/presentations'
    | '/admin/documents'
    | '/admin/domain'
    | '/admin/home'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/presentations'
    | '/admin/team'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/presentations'
    | '/admin/documents'
    | '/admin/domain'
    | '/admin/home'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/presentations'
    | '/admin/team'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/documents'
    | '/domain'
    | '/milestones'
    | '/presentations'
    | '/admin/documents'
    | '/admin/domain'
    | '/admin/home'
    | '/admin/login'
    | '/admin/milestones'
    | '/admin/presentations'
    | '/admin/team'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  DomainRoute: typeof DomainRoute
  MilestonesRoute: typeof MilestonesRoute
  PresentationsRoute: typeof PresentationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/presentations': {
      id: '/presentations'
      path: '/presentations'
      fullPath: '/presentations'
      preLoaderRoute: typeof PresentationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domain': {
      id: '/domain'
      path: '/domain'
      fullPath: '/domain'
      preLoaderRoute: typeof DomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/presentations': {
      id: '/admin/presentations'
      path: '/presentations'
      fullPath: '/admin/presentations'
      preLoaderRoute: typeof AdminPresentationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/milestones': {
      id: '/admin/milestones'
      path: '/milestones'
      fullPath: '/admin/milestones'
      preLoaderRoute: typeof AdminMilestonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/domain': {
      id: '/admin/domain'
      path: '/domain'
      fullPath: '/admin/domain'
      preLoaderRoute: typeof AdminDomainRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminDomainRoute: typeof AdminDomainRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMilestonesRoute: typeof AdminMilestonesRoute
  AdminPresentationsRoute: typeof AdminPresentationsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminDomainRoute: AdminDomainRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMilestonesRoute: AdminMilestonesRoute,
  AdminPresentationsRoute: AdminPresentationsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  DomainRoute: DomainRoute,
  MilestonesRoute: MilestonesRoute,
  PresentationsRoute: PresentationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
